// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Course struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	Subject      string `json:"subject"`
	InstructorID string `json:"instructorID"`
}

type Instructor struct {
	ID        string `json:"id"`
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
	Salary    *int   `json:"salary"`
}

type NewCourse struct {
	Name         string `json:"name"`
	Subject      string `json:"Subject"`
	InstructorID string `json:"instructorID"`
}

type Student struct {
	ID        string    `json:"id"`
	Firstname string    `json:"firstname"`
	Lastname  string    `json:"lastname"`
	Gpa       *int      `json:"GPA"`
	Courses   []*Course `json:"courses"`
}
